### ISSUE TITLE
Firmware 1.x, config update error breaks the script

### ISSUE THREAD

**Issue by Crow79** [shellykauppa/plus-plug-spot-illuminator#2] opened 2023-08-02 19:00 UTC
Script is not working with current beta version 1.0.0-beta6.

See the following log entries for details:
> shelly_ejs_rpc.cpp:41` Shelly.call HTTP.GET {"url":"https://api.spot-hinta.fi/JustNow?region=FI","timeout":2,"ssl_ca":"*"}
> shelly_user_script.:341 JS RAM stat: after user code: 132448 after: 121224, used: 11224
> shelly_notification:163 Status change of script:1: {"id":1,"running":true}
> shos_rpc_inst.c:230 PLUGS_UI.SetConfig via loopback
> shos_rpc_inst.c:230 HTTP.GET via loopback
> shelly_http_client.:304 0x3ffe3df0: HTTPS GET https://api.spot-hinta.fi/JustNow?region=FI (CA *)
> PlusPlugIlluminator: Config update error
> shelly_notification:163 Status change of switch:0: {"id":0,"current":0.000}
> ssl_cli.c:2297 0x3ffe1744 server did not confirm our fragment length request, disabling
> shos_init.c:82 New min heap free: 99848

**Comment by anttikuuskoski** [comment] 2023-08-03 21:04
The problem is on this line: 

https://github.com/shellykauppa/plus-plug-spot-illuminator/blob/de868278b3d6633eb4be77fe2bc2383344e7ef73/shelly/index.js#L250-L251 

It seems that `Object.create()` is either broken or unsupported on 1.0.0-beta6. The resulting object is empty.

A code to demonstrate the bug can be found in [this gist](https://gist.github.com/anttikuuskoski/08c246aba218d74f65c752d55f836dae). 

Since they released the 1.0.0 version today, I hope they've fixed it already. Will report the bug and create a workaround just in case.

**Comment by anttikuuskoski** [comment] 2023-08-03 21:48
It seems that the previous problem is not the only one. Regardless of a per-spec configuration object, the `PLUGS_UI.SetConfig` call keeps failing with an error code of -103.

**Comment by anttikuuskoski** [comment] 2023-08-21 13:27
Renamed issue to include V1.0.0 firmware as well.

After further testing, two different error cases were found with 1.0.0-beta6 firmware:

1. Object.create -function does not work properly or alternatively, the new scripting system fails. See demonstration code in https://gist.github.com/anttikuuskoski/ca6e4b70bc86786ce49d22abe4fac06a wherein an object created with Object.create does not work but another object cloning function does.
2. Call stack depth seems to affect behaviour of Shelly.call (possibly exclusively when "PLUGS_UI.SetConfig" is called). See https://gist.github.com/anttikuuskoski/e1e515d2d4597a40b0fcd56dc41ffbe5 for demonstration where a call to Shelly.call succeeds when called from a call stack of depth 1 but fails when the same function is called from within another level of calls.

Unfortunately, we've received the first error messages that confirm our fears that the issue is still relevant with the now released 1.0.0 firmware.

**Comment by anttikuuskoski** [comment] 2023-08-21 14:08
For those who have upgraded to 1.0.0  but now wish they hadn't, here's the link to 0.14.4 firmware that is still available (21 August 2023) that can be used to downgrade firmware using the "Custom firmware" form on the device's internal firmware settings page. I.e. this cannot be done via app / cloud.

See here: https://github.com/shellykauppa/plus-plug-spot-illuminator/issues/2#issuecomment-1743262660

~~https://firmware.shelly.cloud/gen2/PlusPlugS/8143ca2d47d1e3ab9ecd368c619e4af803a5bb61fd7cf66bf14ff4f797fa7a1f~~

Edit: old firmware no longer available (30 September 2023).

Edit 2: added pointer to the post below for an alternative firmware link.

**Comment by Crow79** [comment] 2023-09-02 16:50
Tested with newest firmware 1.0.2-beta1-3 and still config update error occurs

**Comment by anttikuuskoski** [comment] 2023-09-12 13:59
Tested with 1.0.3, still results in the same error. Also, the two [tests in gist above](https://github.com/shellykauppa/plus-plug-spot-illuminator/issues/2#issuecomment-1686331304) keep showing incorrect behaviour.

**Comment by anttikuuskoski** [comment] 2023-09-12 15:08
The error message in callback is ```-103 Missing or bad argument 'config'!```. So that kind of confirms that it has something to do with the configuration object not being passed correctly.

**Comment by jaak-ko** [comment] 2023-09-30 08:55
Is there a way to bypass the issue somehow? Or has the script just been doomed from now on?

**Comment by anttikuuskoski** [comment] 2023-09-30 09:41
> Is there a way to bypass the issue somehow? Or has the script just been doomed from now on?

@jaak-ko The easy workaround is to use [0.14.x firmware](https://github.com/shellykauppa/plus-plug-spot-illuminator/issues/2#issuecomment-1686405197), that should work unless you really need something from 1.0.3 fw. Other workarounds have not yet surfaced (but might well exist).

I've reported the matter and consequently nagged about it in the [Shelly support fb group](https://www.facebook.com/groups/ShellyIoTCommunitySupport/posts/6394778923954751/) and I'm hopeful a fix will be available sometime in the future.

**Comment by jaak-ko** [comment] 2023-09-30 10:53
> > Is there a way to bypass the issue somehow? Or has the script just been doomed from now on?
> 
> 
> 
> @jaak-ko The easy workaround is to use [0.14.x firmware](https://github.com/shellykauppa/plus-plug-spot-illuminator/issues/2#issuecomment-1686405197), that should work unless you really need something from 1.0.3 fw. Other workarounds have not yet surfaced (but might well exist).
> 
> 
> 
> I've reported the matter and consequently nagged about it in the [Shelly support fb group](https://www.facebook.com/groups/ShellyIoTCommunitySupport/posts/6394778923954751/) and I'm hopeful a fix will be available sometime in the future.

Yes, so I figureg. 

ps. The firmware link just gives me "NoSuchKeyThe specified key does not exist."

**Comment by anttikuuskoski** [comment] 2023-09-30 11:22
> ps. The firmware link just gives me "NoSuchKeyThe specified key does not exist."

Bollocks. So they've removed the old firmware. Please feel free to add some pressure Shelly via fb / support or to try to find a workaround to [issue 2](https://gist.github.com/anttikuuskoski/e1e515d2d4597a40b0fcd56dc41ffbe5), which is currently blocking the script from working (the object copy issue can be worked around using `Object.assign({}, source)`). There's also 1.0.6-beta1 available now that has not been tried so far. I'll give it a try and create a separate branch with the copy issue  resolved later on.

**Comment by anttikuuskoski** [comment] 2023-10-02 15:44
@jaak-ko I found an alternative source for the 0.14.4 firmware, it's downloadable from the links [provided on this page](https://www.shelly-support.eu/forum/thread/21939-downgrade-links-to-0-14-x) and needs to be uploaded manually (i.e. no OTA possible).

Note that although the links point to shelly.cloud urls and so should be legit, I have found no official statement for these firmware so use solely at your own risk. I have successfully used the plus plug s firmware and it seems to provide the 0.14.4  firmware as expected.

**Comment by jaak-ko** [comment] 2023-10-07 10:42
Thanks.

What do you mean by manually uploading? Just drag the zip-file to "Upload custom firmware" or what?

**Comment by anttikuuskoski** [comment] 2023-10-09 11:10
> What do you mean by manually uploading? Just drag the zip-file to "Upload custom firmware" or what?

Yep, meaning that OTA is not possible.

**Comment by adelekottarainen** [comment] 2023-10-11 17:37
Seems to be working again with 1.0.7-beta1. At least now color is matching the price.

**Comment by anttikuuskoski** [comment] 2023-10-11 17:49
> Seems to be working again with 1.0.7-beta1. At least now color is matching the price.

That's wonderful news, thanks @adelekottarainen for reporting! I think we should keep this issue open until the fix has been verified in a mainstream release before closing the issue.

**Comment by adelekottarainen** [comment] 2023-10-11 18:22
Plug just turned purple as price dropped to -0.10 snt/kWh

**Comment by antti-oja** [comment] 2023-10-12 09:55
So, firmware 1.0.7 -beta working? Can somebody help me. I have Shelly Plus plug S.
Script I have copied code:  plus-plug-spot-illuminator/shelly/index.js at main · shellykauppa/plus-plug-spot-illuminator (github.com).  Debug is okay, but it doesn’t work. Error code is “Config update error” Led color is white and doesn’t change.  I´m new user so maybe I do something wrong?

**Comment by Crow79** [comment] 2023-10-12 09:57
Not working for me either. Same config update error and light stays white

**Comment by anttikuuskoski** [comment] 2023-10-12 10:24
Does not work for me either. @adelekottarainen is it still running for you in 1.0.7-beta1?

Please note that the code does contain the failing (incorrect since fw 1.0) Object.create call so it is not entirely surprising. I just pushed a fix for that one, but the core of the matter still remains (i.e. something broken in scripting engine).

**Comment by Crow79** [comment] 2023-10-12 10:27
Now I'm getting this: PPI: Config update error -103 Missing or bad argument 'config'!

**Comment by adelekottarainen** [comment] 2023-10-12 17:40
> Does not work for me either. @adelekottarainen is it still running for you in 1.0.7-beta1?
> 
> Please note that the code does contain the failing (incorrect since fw 1.0) Object.create call so it is not entirely surprising. I just pushed a fix for that one, but the core of the matter still remains (i.e. something broken in scripting engine).

Yes. No problem yet. Though e-price has been like dead man's brain scan.
(Yesterday I tried different colors and price ranges without problems) 

Unfortunately I cannot stare the plug 24/7 like 'mykkä pillua'.

**Comment by adelekottarainen** [comment] 2023-10-12 17:46
The plugs where script seems to work are brand new ones, which came with 1.0.3. I haven't have chance to try it with older plugs. Factory reset needed?

**Comment by antti-oja** [comment] 2023-10-12 18:47
> Now I'm getting this: PPI: Config update error -103 Missing or bad argument 'config'!

I have same error

**Comment by anttikuuskoski** [comment] 2023-10-12 20:31
> > Now I'm getting this: PPI: Config update error -103 Missing or bad argument 'config'!

Tried performing a factory reset with the old device, tried a brand new device but to no avail. 

Also just remembered why I had been holding back on the change in ef6f9e0; that one breaks support for 0.14.x (duh). So I'll revert it and move it over to a new branch for 1.x support.

Btw. please leave rudeness and sexual references outside this repository.

**Comment by Crow79** [comment] 2023-10-31 17:54
Tested with release v. 1.0.7. Same error still.

**Comment by anttikuuskoski** [comment] 2023-11-10 22:24
I just committed a fix into [1.x branch](https://github.com/shellykauppa/plus-plug-spot-illuminator/tree/fw-1.x-support) that should make the script work with 1.x firmware. Did a preliminary test with 1.0.8 fw and it seems to work.

The workaround to dysfunctional UI_PLUGS API is to use an RPC that does not seem equally handicapped. Kudos go to @Spot-hinta-fi people (copied the solution from their [street light script](https://github.com/Spot-hinta-fi/Shelly/blob/main/Scripts/Shelly-PlusPlugS-StreetLight.js). It never occurred to me to use the RPC...

I'll merge this branch to master after trying it out for a day or two. Confirmation on whether it works/doesn't would be appreciated!

Edit: Added a pointer to the fw-1.x-support branch.

**Comment by Crow79** [comment] 2023-11-11 18:27
I have been testing the script with the workaround added and seems to be working correctly.

**Comment by Spot-hinta-fi** [comment] 2023-11-11 18:33
Hi, glad to hear if this script is also working now. I actually implemented the "street light" script to exactly figure out how to make this work in 1.0.x firmwares.

**Comment by Crow79** [comment] 2023-11-11 20:44
> Hi, glad to hear if this script is also working now. I actually implemented the "street light" script to exactly figure out how to make this work in 1.0.x firmwares.

Great job with the street light script. I have been using it also.

**Comment by Crow79** [comment] 2023-11-14 18:27
With 1.1.0-beta1 firmware script seems to be broken again. Following error is shown:
> PPI: Config update error -104 -104: Timed out

@Spot-hinta-fi Same error with street light script.
> PlusPlugS-StreetLight: Color change was not successful. Error code: -104 - Error message: -104: Timed out

**Comment by Spot-hinta-fi** [comment] 2023-11-14 18:34
> With 1.1.0-beta1 firmware script seems to be broken again. Following error is shown:
> > PPI: Config update error -104 -104: Timed out
> 
> @Spot-hinta-fi Same error with street light script.
> > PlusPlugS-StreetLight: Color change was not successful. Error code: -104 - Error message: -104: Timed out

It starts to be a full time job to test new firmware versions.  I just wonder whats the point to release this often new firmware versions which seems to break something always.  Well...this is only a "beta1" version, but stil.... that RPC call should be very much basic functionality.

**Comment by Spot-hinta-fi** [comment] 2023-11-14 20:41
I tested now with 1.1.0-Beta2 which was released later today and now it seems to work.  They did some fixes affecting Shelly Plus Plug S and this potentially got fixed by that also.

**Comment by anttikuuskoski** [comment] 2023-11-14 20:54
> It starts to be a full time job to test new firmware versions. I just wonder whats the point to release this often new firmware versions which seems to break something always.

I've been wondering the same. Software quality control is definitively not one of their strong suits currently, I really really hope they get their ship straight in this regard and preferably sooner than later.

**Comment by Crow79** [comment] 2023-11-15 18:20
Both scripts are working again with the latest 1.1.0-beta2 version.

**Comment by anttikuuskoski** [comment] 2023-12-03 21:09
Worked for a few weeks straight so I'd say it works. Merged the changes back to main and closing this issue as fixed.

**Closed as completed** 2023-12-03 21:10 UTC
